# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultipleFunction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultipleFunction

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'RxDataSources'

  pod 'RealmSwift'
  
  target 'MultipleFunctionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultipleFunctionUITests' do
    # Pods for testing
  end

end
